name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "v14.x"

      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn eslint

      - run: yarn stylelint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "v14.x"

      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn test --coverage

      - run: bash <(curl -s https://codecov.io/bash)
